language: php

matrix:
  allow_failures:
    - php: hhvm

php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - hhvm

before_script:
    - composer self-update
    - composer install --dev

script: vendor/bin/phpunit

